config/routes.rb
Rails.application.routes.draw do
  resources :posts, :categories, :tags do
    get 'confirm_delete', on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  # CRUD adds default ordered scope
  scope :ordered, -> { order(updated_at: :desc) }
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts

  validates :name, presence: true
  validates :name, uniqueness: true

  # has_scope scopes
  scope :by_name, ->(name) { where('LOWER(name) LIKE ?', "%#{name.downcase}%") }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category
  has_and_belongs_to_many :tags

  validates :category, presence: true
  validates :title, presence: true
  validates :title, uniqueness: true

  alias_attribute :name, :title

  # has_scope scopes
  scope :by_title, (lambda do |title|
    where('LOWER(title) LIKE ?', "%#{title.downcase}%")
  end)
  scope :by_tag_id, (->(id) { joins(:tags).where(tags: { id: id }) })
  scope :by_category_id, (->(id) { where(category_id: id) })
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :posts

  validates :name, presence: true
  validates :name, uniqueness: true

  # has_scope scopes
  scope :by_name, ->(name) { where('LOWER(name) LIKE ?', "%#{name.downcase}%") }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  has_scope :by_name

  include CruddyControllerMixin

  class << self
    def filters
      {
        by_name: {
          type: :string,
          label: 'Name'
        }
      }
    end
  end

  private

  def safe_params
    params.require(:category).permit(
      :name
    )
  end

  def klass
    Category
  end
  helper_method :klass
end

app/controllers/concerns/cruddy_controller_mixin.rb
# DRY up CRUD ops for controllers
module CruddyControllerMixin
  extend ActiveSupport::Concern

  # expose current_set and current_object as helper methods
  included do
    helper_method :current_set
    helper_method :current_object
  end

  def index; end

  def show; end

  def edit; end

  def confirm_delete; end

  def new
    @current_object = klass.new
  end

  def create
    @current_object = klass.new(safe_params)

    if current_object.save
      redirect_to(
        index_path,
        notice: notice("Successfully created #{current_object.name}!")
      )
    else
      render :new, alert: 'There was an error'
    end
  end

  def update
    if current_object.update(safe_params)
      redirect_to(
        index_path,
        notice: notice("Successfully updated #{current_object.name}!")
      )
    else
      render :edit, alert: 'There was an error'
    end
  end

  def destroy
    if current_object.destroy
      redirect_to(
        index_path,
        notice: "Successfully deleted #{current_object.name}!"
      )
    else
      redirect_back fallback_location: root_path,
                    alert: current_object.errors.full_messages.join(', ')
    end
  end

  private

  # default redirect_to path after save / destroy
  def index_path
    { action: :index }
  end

  # notice on successful save
  def notice(message)
    %(#{message} <a class="btn btn-xs btn-default" ) +
      %(href="#{url_for(action: :edit, id: current_object)}">) +
      %(<i class="fa fa-pencil"></i> Edit again</a>)
  end

  # return memoized @current_set - a paginated, scoped set of records
  def current_set
    return @current_set if defined? @current_set
    query = apply_scopes(klass)
    query = query.ordered
    @current_set = extend_current_set(query.page(params[:page]))
  end

  # allow controller to override the current_set query
  def extend_current_set(query)
    query
  end

  # return memoized @current_object
  def current_object
    @current_object ||= klass.find(params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  has_scope :by_title
  has_scope :by_tag_id
  has_scope :by_category_id

  include CruddyControllerMixin

  class << self
    def filters
      {
        by_title: {
          type: :string,
          label: 'Title'
        },
        by_tag_id: {
          type: :select,
          label: 'Tags',
          collection: Tag.pluck(:name, :id)
        },
        by_category_id: {
          type: :select,
          label: 'Categories',
          collection: Category.pluck(:name, :id)
        }
      }
    end
  end

  private

  def safe_params
    params.require(:post).permit(
      :title,
      :text,
      :category_id,
      tag_ids: []
    )
  end

  def klass
    Post
  end
  helper_method :klass

  def extend_current_set(query)
    query.includes(:category, :tags)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  has_scope :by_name

  include CruddyControllerMixin

  class << self
    def filters
      {
        by_name: {
          type: :string,
          label: 'Name'
        }
      }
    end
  end

  private

  def safe_params
    params.require(:tag).permit(
      :name
    )
  end

  def klass
    Tag
  end
  helper_method :klass
end

app/helpers/application_helper.rb
# Application-wide helper methods
module ApplicationHelper
  ALERT_TYPES = [:success, :info, :warning, :danger] unless const_defined?(:ALERT_TYPES)

  # https://github.com/bootstrap-ruby/rails-bootstrap-forms/blob/master/lib/bootstrap_form/helpers/bootstrap.rb#L14-L31
  def form_errors(object, title = nil, options = {})
    css = options[:class] || 'bs-callout bs-callout-danger'
    return unless object.respond_to?(:errors) &&
                  object.errors.full_messages.any?
    title ||= "#{pluralize(object.errors.full_messages.length, 'Error')} " \
      'prevented this from saving:'
    content_tag :div, class: css do
      concat content_tag :h4, title if title
      concat error_summary(object) unless options[:error_summary] == false
    end
  end

  def bootstrap_flash(options = {})
    flash_messages = []
    flash.each do |type, message|
      # Skip empty messages, e.g. for devise messages set to nothing in a locale file.
      next if message.blank?

      type = type.to_sym
      type = :success if type == :notice
      type = :danger  if type == :alert
      type = :danger  if type == :error
      next unless ALERT_TYPES.include?(type)

      tag_class = options.extract!(:class)[:class]
      tag_options = {
        class: "alert fade in alert-#{type} #{tag_class}"
      }.merge(options)

      close_button = content_tag(:button, raw("&times;"), type: "button", class: "close", "data-dismiss" => "alert")

      Array(message).each do |msg|
        text = content_tag(:div, close_button + msg.try(:html_safe), tag_options)
        flash_messages << text if msg
      end
    end
    flash_messages.join("\n").html_safe
  end

  def page_title
    if content_for?(:title)
      yield(:title)
    else
      path = request.path.split('/').reject { |i| i == 'admin' }
      "Crud#{path.map(&:titleize).join(' | ')}"
    end
  end
end

app/views/application/_action_links.html.slim
- only ||= [:show, :edit, :destroy]
- extra_class ||= ' btn-xs'
- can_delete = !!Rails.application.routes.recognize_path("#{params[:controller]}/:id", method: :delete) rescue false

- if only.include?(:back)
  = link_to 'Back', url_for(action: :index),
    class: "btn btn-default#{extra_class}"
  '

- if only.include?(:show)
  = link_to %(#{fa_icon('eye')} Show).html_safe,
    url_for(action: :show, id: obj),
    class: "btn btn-default#{extra_class}"
  '

- if only.include?(:edit)
  = link_to %(#{fa_icon('pencil')} Edit).html_safe,
    url_for(action: :edit, id: obj),
    class: "btn btn-default btn-warning#{extra_class}"
  '

- if only.include?(:destroy) && can_delete
  = link_to %(#{fa_icon('trash-o')} Delete).html_safe,
    url_for(action: :confirm_delete, id: obj), class: "btn btn-danger#{extra_class}"

app/views/application/_actions.html.slim
.form-group.clearfix
  button.btn.btn-primary type="submit"
    = %(#{fa_icon('save')} Save).html_safe
  '
  = link_to %(#{fa_icon('remove')} #{t('.cancel', default: t("helpers.links.cancel"))}).html_safe,
    url_for(action: :index), class: 'btn btn-default'

app/views/application/_filter_actions.html.slim
.form-group
  button.btn.btn-success
    = %(#{fa_icon('filter')} Filter).html_safe
  '
  = link_to %(#{fa_icon('remove')} Clear Filters).html_safe,
    request.fullpath.split('?').first, class: 'btn btn-default'

app/views/application/_filters.html.slim
- if controller.class.respond_to?(:filters) && (filters = controller.class.filters)

  = simple_form_for klass.name.to_sym, method: :get, url: '',
    wrapper: :inline_form, html: { class: 'form-inline filter-form' } do |f|

    - filters.each do |attr, opts|
      - param_name = opts[:param_name] || attr
      - label = opts[:label] || attr.to_s.titleize
      - case opts[:type]
      - when :string
        = f.input attr, input_html: { name: param_name,
          value: params[param_name] }, required: false, placeholder: label
        '
      - when :select
        - all = "- All #{label.to_s.pluralize} -"
        - multiple = opts[:multiple].present?
        - if multiple
          - blank_opt = false
        - else
          - blank_opt = params[param_name].blank? ? '' : all
        - selected = params[param_name]
        - input_param_name = param_name
        - input_param_name = "#{input_param_name}[]" if multiple
        - if opts[:remote_url].present?
          - if opts[:klass] && params[param_name].present?
            - val = params[param_name]
            - val.reject!(&:blank?) if val.is_a? (Array)
            - collection = multiple.present? ? opts[:klass].where(id: val) : opts[:klass].find_by(id: val)
          - else
            - collection = []

          = f.input attr, as: :remote_select, url: opts[:remote_url],
            multiple: multiple,
            collection: collection, input_html: { name: input_param_name,
            data: { allow_clear: true, placeholder: label } },
            include_blank: label, selected: selected
        - else
          - select_options = { collection: opts[:collection], selected: selected,
                               input_html: { name: input_param_name, multiple: multiple,
                               data: { placeholder: label, allow_clear: true } },
                               required: false, include_blank: all }
          - select_options[:as] = opts[:as] if opts[:as]
          - select_options[:group_method] = opts[:group_method] if opts[:group_method]
          = f.input attr, select_options

        '
      - when :datetime
        = f.input attr, input_html: { name: param_name, class: 'datetimepicker',
          value: params[param_name] }, required: false, placeholder: label
        '
      - when :range
        - last_key = opts[:options].keys.last
        - opts[:options].each do |k,v|
          - value = params[attr].present? ? params[attr][k] : nil
          = f.input k, input_html: { name: attr.to_s + "[#{k.to_s}]",
            value: value, class: 'datetimepicker' }, required: false,
            placeholder: v
          - if k == last_key
            '
          - else
            ' &nbsp;&mdash;
      - when :boolean
        = f.input attr, as: :boolean, required: false, label: "#{label}?",
          wrapper: :vertical_boolean, input_html: { name: param_name,
          checked: (params[param_name] == '1') }
        '

    = render 'filter_actions'

  hr

app/views/application/_form.html.slim
- wrapper = controller.class.try(:form_wrapper) || :vertical_form
- css_class = controller.class.try(:form_class) || ''
= simple_form_for current_object, wrapper: wrapper,
  html: { class: css_class } do |f|
  /= form_errors(f.object)
  = render 'fields', f: f
  = render 'actions', f: f

app/views/application/_index_header.html.slim
div class="page-header"

  .actions.pull-right
    - if controller.respond_to?(:csv_cols)
      = link_to %(#{fa_icon('download')} Download CSV - #{number_with_delimiter(current_set.total_count)} rows).html_safe,
        url_for(params.merge(format: :csv)), class: 'btn btn-primary'
      '
    = link_to %(#{fa_icon('plus')} #{t('.new', default: ['New %{model}'], model: klass.model_name.human.titleize)}).html_safe,
      url_for(action: :new), :class => 'btn btn-primary'

  h1 = t '.title', default: klass.model_name.human.pluralize.titleize

app/views/application/_pagination.html.slim
- records ||= current_set
.pagination-wrap
  = paginate records
  p.pagination-info = page_entries_info records

app/views/application/_show.html.slim
dl.dl-horizontal
  dt = klass.human_attribute_name(:name) + ':'
  dd = current_object.try(:name)

app/views/application/_table.html.slim
= render 'pagination', current_set: current_set

table class="table table-striped table-with-actions"
  thead
    = render 'table_head'
  tbody
    = render current_set

= render 'pagination', current_set: current_set

app/views/application/confirm_delete.html.slim
div class="page-header"
  h1 = "Are you sure you want to delete #{current_object.name}?"

h3 = "#{fa_icon('warning')} Deletion is irreversible".html_safe

= simple_form_for current_object, method: :delete do |f|
  .form-group.clearfix
    button.btn.btn-danger type="submit"
      = %(#{fa_icon('trash')} Delete).html_safe
    '
    = link_to %(#{fa_icon('remove')} Cancel).html_safe,
      url_for(action: :index), class: 'btn btn-default'

app/views/application/edit.html.slim
div class="page-header"
  h1 = "Edit #{klass.model_name.human.titleize}"
= render 'form'

app/views/application/index.html.slim
= render 'index_header'

= render 'filters'

= render 'table'

app/views/application/new.html.slim
div class="page-header"
  h1 = "New #{klass.model_name.human.titleize}"
= render 'form'

app/views/application/show.html.slim
div class="page-header"

  .actions.pull-right
    = render "action_links", obj: current_object,
      only: [:back, :edit, :destroy], extra_class: ''

  h1 = klass.model_name.human.titleize

= render 'show'

app/views/categories/_category.html.slim
tr
  td = category.id
  td = category.name
  td = l category.created_at
  td = l category.updated_at
  td = render 'action_links', obj: category

app/views/categories/_fields.html.slim
= f.input :name

app/views/categories/_table_head.html.slim
tr
  th ID
  th Name
  th Created at
  th Updated at
  th Actions

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= page_title
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"


  body
    .navbar.navbar-default.navbar-static-top
        .container
          button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand href="#"Crud
          .navbar-collapse.collapse.navbar-responsive-collapse
            ul.nav.navbar-nav
              li= link_to "Posts", posts_path
              li= link_to "Categories", categories_path
              li= link_to "Tags", tags_path

    .container
      .row
        .col-lg-12
          = bootstrap_flash.html_safe
          = yield

      footer
        p &copy; Cruddy Rails 2017

app/views/posts/_fields.html.slim
= f.input :title
= f.association :category
= f.association :tags
= f.input :text

app/views/posts/_post.html.slim
- tags = post.tags.map { |tag| link_to(tag.name, tag) }
tr
  td = post.id
  td = post.title
  td = link_to post.category.name, post.category
  td = tags.join(', ').html_safe
  td = post.text
  td = l post.created_at
  td = l post.updated_at
  td = render 'action_links', obj: post

app/views/posts/_table_head.html.slim
tr
  th ID
  th Name
  th Category
  th Tags
  th Text
  th Created at
  th Updated at
  th Actions

app/views/tags/_fields.html.slim
= f.input :name

app/views/tags/_table_head.html.slim
tr
  th ID
  th Name
  th Created at
  th Updated at
  th Actions

app/views/tags/_tag.html.slim
tr
  td = tag.id
  td = tag.name
  td = l tag.created_at
  td = l tag.updated_at
  td = render 'action_links', obj: tag